- hosts: all

  tasks:
    - apt:
        name: python3-pip
        update_cache: yes
        cache_valid_time: 604800 # 1 week

    - name: Ignore PEP 668 because it's silly.
      ansible.builtin.file:
        path: /usr/lib/python3.11/EXTERNALLY-MANAGED
        state: absent

    - pip:
        name: docker
