- hosts: all

  tasks:
    - apt:
        name: python3-pip
        update_cache: yes
        cache_valid_time: 604800 # 1 week
      tags:
        - setup

    - name: Ignore PEP 668 because it's silly.
      ansible.builtin.file:
        path: /usr/lib/python3.11/EXTERNALLY-MANAGED
        state: absent

    - pip:
        name: docker
      tags:
        - setup

    - name: start redmine container
      community.docker.docker_container:
        name: redmine
        image: redmine
        published_ports: 3000:3000
        env:
          REDMINE_DB_POSTGRES: "{{ REDMINE_DB_POSTGRES }}"
          REDMINE_DB_PORT: "{{ REDMINE_DB_PORT }}"
          REDMINE_DB_USERNAME: "{{ REDMINE_DB_USERNAME }}"
          REDMINE_DB_DATABASE: "{{ REDMINE_DB_DATABASE }}"
          REDMINE_DB_PASSWORD: "{{ REDMINE_DB_PASSWORD }}"
      become: yes
      tags:
        - redmine
