- hosts: all
  tasks:
    - name: pythin3-pip
      apt:
        name: python3-pip
        update_cache: yes
        cache_valid_time: 604800 # 1 week
      tags:
        - setup
    - name: Ignore PEP 668 because it's silly.
      ansible.builtin.file:
        path: /usr/lib/python3.11/EXTERNALLY-MANAGED
        state: absent
      tags:
        - setup
    - name: pip
      pip:
        name: docker
      tags:
        - setup
    - name: create .env
      ansible.builtin.template:
        src: env.template
        dest: .env
        mode: '0644'
    - name: start redmine container
      community.docker.docker_container:
        name: redmine
        image: redmine
        published_ports: 3000:3000
        env_file: .env
      become: yes

- hosts: webservers
  tasks:
    - name: start datadog
      import_role:
        name: datadog.datadog
      become: yes
      tags:
        - datadog
